### ISSUE TITLE
Unable to delete a node managed by Karpenter in EKS+Fargate setup

### ISSUE THREAD

**Issue by BrandonEscamilla** [aws-ia/terraform-aws-eks-blueprints-addons#314] opened 2023-11-14 16:52 UTC
- [X ] ✋ I have searched the open/closed issues and my issue is not listed.

Description
I am facing an issue with my EKS cluster using the ﻿terraform-aws-eks-blueprints addons and Karpenter with Fargate. I have a deployment where I can set the replicas to 0 to delete the nodes associated with it. However, there is one particular node that was not deleted for some unknown reason and Karpenter keeps rescheduling a new node to replace it. I have tried various approaches to delete the node, but Karpenter continues to recreate it. Everything seems to work fine with the exception of this node that I can't delete.

Karpenter version: 19.17.4
eks_blueprints_addons version: 1.9.2

Additional Context
I have already tried deleting the node manually using various ﻿kubectl commands, but Karpenter recreates it. The node is still present even when no pods should be running on it. Any help or guidance in resolving this issue would be appreciated.

**Comment by bryantbiggs** [comment] 2023-11-15 15:48
Its hard to say without a reproduction, but if Karpenter is creating a node then that means it is seeing pods in the scheduling queue that need to be scheduled onto a node. Closing for now since I don't think this is specific to the project

**Closed by bryantbiggs** 2023-11-15 15:48 UTC
Labels: question
