### ISSUE TITLE
KEDA support

### ISSUE THREAD

**Issue by blakepettersson** [aws-ia/terraform-aws-eks-blueprints-addons#264] opened 2023-09-25 07:41 UTC
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

#### What is the outcome that you are trying to reach?

We currently use [KEDA](https://keda.sh/). It has a lot of different scalers, and a lot of ways to configure it. The scalers of interest (and hence the IAM policies) for this repo would be all the AWS-related ones (DynamoDB, Cloudwatch, SQS etc etc). Other scaler configurations should be able to be added though.

#### Describe the solution you would like

A way to configure KEDA similar to external-dns, karpenter etc.

**Comment by askulkarni2** [comment] 2023-09-26 04:30
Duplicate of #245

**Closed by askulkarni2** 2023-09-26 04:30 UTC
