### ISSUE TITLE
The parameter names are not updated to meet the new parameter names in Karpenter 0.23.0

### ISSUE THREAD

**Issue by nalshamaajc** [aws-ia/terraform-aws-eks-blueprints-addons#21] opened 2023-03-06 18:26 UTC
The parameter names are not updated to meet the new parameter names in Karpenter 0.23.0 which causes an issue with the parameters not propagating properly to the Karpenter helm chart because addons still uses the old parameter names.

https://github.com/aws-ia/terraform-aws-eks-blueprints/blob/a9181ae2ddfafc03af70b1eab667eac7dd17bf1a/modules/kubernetes-addons/karpenter/locals.tf#L46-L52

![image](https://user-images.githubusercontent.com/114491638/223183506-faaebd75-37c8-497a-9176-0bd000d4c57e.png)
![image](https://user-images.githubusercontent.com/114491638/223184117-183e7015-0de4-42f0-a7f8-8edd21cde591.png)

**Comment by rodrigobersa** [comment] 2023-03-17 19:04
Hi nalshamaajc!

As we spoke, in order enable the configuration of the parameters in the first image:
![Screen Shot 2023-03-13 at 7 01 41 PM](https://user-images.githubusercontent.com/23385273/224851373-0b3500df-ef15-4bc2-8a62-788504d69be7.png)

You'll need to add another configuration block, together with the one that you highlighted:
https://github.com/aws-ia/terraform-aws-eks-blueprints/blob/a9181ae2ddfafc03af70b1eab667eac7dd17bf1a/modules/kubernetes-addons/karpenter/locals.tf#L46-L52

```
  argocd_gitops_config = {
    enable                 = true
    serviceAccount         = {
      name   = local.service_account
      create = false
    }
    settings = {
      aws = {
        clusterName            = var.addon_context.eks_cluster_id
        clusterEndpoint        = var.addon_context.aws_eks_cluster_endpoint
        defaultInstanceProfile = var.node_iam_instance_profile
        interruptionQueueName  = try(data.aws_arn.queue[0].resource, "")
      }
    }
  }
```

**Comment by nalshamaajc** [comment] 2023-03-20 18:21
Thanks @rodrigobersa! 
We also needed to pass the `defaultInstanceProfile` through the TF outputs which made it work eventually.

**Comment by nalshamaajc** [comment] 2023-03-31 18:12
I reopened the issue since it is still cause problems when pulling from upstream the values are still different from the ones in the helm chart

https://github.com/aws-ia/terraform-aws-eks-blueprints/blob/v4.27.0/modules/kubernetes-addons/karpenter/locals.tf#L46-L52

**Comment by bwagner5** [comment] 2023-05-12 14:27
@nalshamaajc does https://github.com/aws-ia/terraform-aws-eks-blueprints-addons/pull/115 not fix this issue?  Maybe I'm not understanding which parameter is incorrect.

It looks like where this is defined is correct:

https://github.com/aws-ia/terraform-aws-eks-blueprints-addons/pull/115/files#diff-dc46acf24afd63ef8c556b77c126ccc6e578bc87e3aa09a931f33d9bf2532fbbR1946

https://github.com/aws/karpenter/tree/main/charts/karpenter#installing-the-chart
```
settings.aws.defaultInstanceProfile
```

**Comment by bryantbiggs** [comment] 2023-05-12 14:32
@nalshamaajc would you mind providing a reproduction so we can take a look at the issue you are facing? thanks!

**Comment by bryantbiggs** [comment] 2023-05-27 21:42
closing this for now - please feel free to respond if there is additional details and we can take a look

**Closed by bryantbiggs** 2023-05-27 21:42 UTC
Labels: question
