### ISSUE TITLE
aws-eks-blueprints-addons module "aws-ebs-csi" is missing role and policy creation.

### ISSUE THREAD

**Issue by SmithaRangappaGitHub** [aws-ia/terraform-aws-eks-blueprints-addons#225] opened 2023-08-08 07:39 UTC
## Description

aws-eks-blueprints-addons module "aws-ebs-csi" is not creating role and policy.

## Versions

- Module version [Required]: Using Latest tag 1.5.0 which is having addon_version = "v1.21.0-eksbuild.1" for ebs-csi

- Terraform version:
v1.4.0
- Provider version(s):
- Using previously-installed hashicorp/time v0.9.1
- Using previously-installed gavinbunney/kubectl v1.14.0
- Using previously-installed hashicorp/random v3.5.1
- Using previously-installed hashicorp/null v3.2.1
- Using previously-installed hashicorp/local v2.4.0
- Using previously-installed hashicorp/kubernetes v2.21.1
- Using previously-installed terraform-aws-modules/http v2.4.1
- Using previously-installed hashicorp/tls v4.0.4
- Using previously-installed hashicorp/cloudinit v2.3.2
- Using previously-installed hashicorp/helm v2.10.1
- Using previously-installed hashicorp/aws v5.6.2

terraform init
terraform plan
Terraform will perform the following actions:

  # module.eks_blueprints_addons.aws_eks_addon.this["aws-ebs-csi-driver"] will be created
  + resource "aws_eks_addon" "this" {
      + addon_name                  = "aws-ebs-csi-driver"
      + addon_version               = "v1.21.0-eksbuild.1"
      + arn                         = (known after apply)
      + cluster_name                = "eks-cluster"
      + configuration_values        = (known after apply)
      + created_at                  = (known after apply)
      + id                          = (known after apply)
      + modified_at                 = (known after apply)
      + preserve                    = true
      + resolve_conflicts_on_create = "OVERWRITE"
      + resolve_conflicts_on_update = "OVERWRITE"
      + tags                        = {
          + "Environment" = "prod"
        }
      + tags_all                    = {
          + "Environment" = "prod"
        }

      + timeouts {}
    }

## Expected behaviour

Missing irsa role and policy:

aws_iam_role.irsa
aws_iam_policy.aws_ebs_csi_driver

## Actual behaviour
Creating only below module
module.eks_blueprints_addons.aws_eks_addon.this["aws-ebs-csi-driver"]

**Comment by bryantbiggs** [comment] 2023-08-08 14:56
duplicate of #186

**Closed by bryantbiggs** 2023-08-08 14:56 UTC
Labels: question
